name: Build, Test, Deploy

on:
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          script: |
            cd /srv/ekranas
            git pull origin master
            git status
            npm install
            npm run build
            pm2 stop all
            pm2 delete all
            cd /srv
            pm2 start ecosystem.config.js
            pm2 save